// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdWUT1f9ZKQFF0tjzncyBhdeg2XeRhb8',
    appId: '1:609155291157:web:a7b1508f5cd6544cfb961c',
    messagingSenderId: '609155291157',
    projectId: 'just-in-84847',
    authDomain: 'just-in-84847.firebaseapp.com',
    storageBucket: 'just-in-84847.firebasestorage.app',
    measurementId: 'G-WLXJW3ZB17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJVq6CvtWy6K4WXp-glk5eOEO4j7VJ6Es',
    appId: '1:609155291157:android:e0441cf9fd3e8c2dfb961c',
    messagingSenderId: '609155291157',
    projectId: 'just-in-84847',
    storageBucket: 'just-in-84847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJZMb6-SzQleYOeaFtnbqdHl5CmwyDF-s',
    appId: '1:609155291157:ios:03a3e4f655b98cf1fb961c',
    messagingSenderId: '609155291157',
    projectId: 'just-in-84847',
    storageBucket: 'just-in-84847.firebasestorage.app',
    iosBundleId: 'com.example.securityGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJZMb6-SzQleYOeaFtnbqdHl5CmwyDF-s',
    appId: '1:609155291157:ios:03a3e4f655b98cf1fb961c',
    messagingSenderId: '609155291157',
    projectId: 'just-in-84847',
    storageBucket: 'just-in-84847.firebasestorage.app',
    iosBundleId: 'com.example.securityGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdWUT1f9ZKQFF0tjzncyBhdeg2XeRhb8',
    appId: '1:609155291157:web:9a397b773f1c973dfb961c',
    messagingSenderId: '609155291157',
    projectId: 'just-in-84847',
    authDomain: 'just-in-84847.firebaseapp.com',
    storageBucket: 'just-in-84847.firebasestorage.app',
    measurementId: 'G-ZHKRFNLC56',
  );

}